### ISSUE TITLE
Unable to Fetch Data from SQLite Database : attempt to write a readonly database (1544)

### ISSUE THREAD

**Issue by drazicmartin** [fr-ser/grafana-sqlite-datasource#130]
**Describe the bug**
It seam like the Grafana is trying to write into my data.db but does not have write access. I don't want grafana to have it.
I simply want him to fetch data from my backend using pocket-base that use SQlite database under the hood. So I simply point data source to the `data.db` file.
The [FAQ](https://github.com/fr-ser/grafana-sqlite-datasource/blob/main/docs/faq.md#i-have-a-permission-denied-error-for-my-database) says that it is fine if the plugins only have read-access : 
> Make sure, that you have access to the file and all the folders in the path of the file. Read access is enough for the plugin.

But after some time a simple query like `SELECT * FROM [table]` raise an error
```
Status: 500. Message: attempt to write a readonly database (1544)
```

**To Reproduce**

1. start the given `docker-compose` file
2. In grafana add the data-source
  - ![image](https://github.com/fr-ser/grafana-sqlite-datasource/assets/41931010/d174a440-05de-4d7c-8318-819443bfc882)
3. Add some data to pocket-base UI
  - `http://localhost:8090/_` 
4. Create a new dashboard and query
  - `SELECT * FROM [table]`
5. after some time (2/3 min) and multiples query attempt the error should apear.

**Screenshots**
![image](https://github.com/fr-ser/grafana-sqlite-datasource/assets/41931010/f1d2344b-0f79-464a-8115-b37402231dcc)

**Versions:**

- Run via docker?
  - Yes
  - Chrome
- Grafana Version [e.g. 7.3.3]
  - 10.3.3
- Plugin Version [e.g. 0.2.1]
  - 3.4.0
- Plugin installed via grafana-cli or manually?
  - done by docker-compose ENV VAR

**Additional context**

Here is my docker-compose file
```yaml
services:
  pb:
    build: ./pb
    volumes:
     - db-data:/pb/pb_data
    ports:
      - "8090:8080"
    working_dir: /app/pb
  
  grafana:
    image: grafana/grafana-oss
    environment:
      GF_INSTALL_PLUGINS: frser-sqlite-datasource
    ports:
     - "3000:3000"
    volumes:
     - grafana-storage:/var/lib/grafana
     - db-data:/data_from_pb_service

volumes:
  db-data:
  grafana-storage:
```

I hope it's clear. If you have any questions, feel free to ask!
